development:
  ## Affect a static value like:
  secret_key_base: 3803b5ac6c902a644a906a67b516ddfe00f40d489391508f81ec6abcaf3cc8ac94d9f5ae17c667e0f3fb418260a0de3a426d35af9e37e3f6adfaf5cef4de1e1f
  ## or read the value from ENV variable like:
  # secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  ## Also you can set a static value overridable by ENV variable like:
  # secret_key_base: <%= ENV.fetch( "SECRET_KEY_BASE" ) { "3803b5ac6c902a644a906a67b516ddfe00f40d489391508f81ec6abcaf3cc8ac94d9f5ae17c667e0f3fb418260a0de3a426d35af9e37e3f6adfaf5cef4de1e1f" } %>
  ## The first and the last options are the same result of "config_order" in our "config_loader.rb"
production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
